version: '3.3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring
    user: "104"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web
      - "traefik.http.routers.grafana.rule=Host(`grafana.c4.slimprepdevops.com`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  grafana_data: {}

networks:
  default:
    external:
      name: proxy